# Generated by Django 5.1.7 on 2025-12-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_reference_payment_prontu_checkout_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='prontu', max_length=50)),
                ('order_id', models.CharField(blank=True, max_length=80)),
                ('prontu_transaction_id', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('operation', models.CharField(blank=True, max_length=30)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'prontu_transaction_id'], name='payments_pa_provide_7cda36_idx'), models.Index(fields=['order_id'], name='payments_pa_order_i_b1c849_idx')],
            },
        ),
    ]
